# Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal
# numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, 
# is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are 
# pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

from utils import sortedList
import time

startTime = time.time()

pentagonal = lambda n : n*(3*n - 1)//2

pentagonalList = sortedList([])

size = 2750
for n in range(1, size):
    pentagonalList.add(pentagonal(n))
    

D = pentagonalList[-1] - pentagonalList[0]
for j in range(len(pentagonalList)):
    if not j % (size//100):
        print('.', end="", flush=True)
        
    for k in range(j, len(pentagonalList)):
            
        pj = pentagonalList[j]
        pk = pentagonalList[k]
        
        dkj = pk - pj
        # if dkj > D:
            # break
            
        dkpj = pk + pj
        
        # if dkpj > pentagonalList[-1]:
            # break
        
        if dkpj in pentagonalList and dkj in pentagonalList:
            D = dkj if dkj < D else D
            
            
print(D)
print(time.time() - startTime)


