#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/*The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first 
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int factorNumber(int n);

int main()
{
    printf("Euler 12\n");

    int number = 1;
    int numberOfFactor = 1;
    int limit = 500;

    int i = 2;
    while(1){
        numberOfFactor = factorNumber(number);

        if(numberOfFactor >= limit){
            break;
        }

        number += i++;
    }

    printf("%d\n", number);

    return 0;
}


int factorNumber(int n){
    int factor = 2;
    int max = sqrt(n);

    for(int i = 2 ; i <= max ; i++){
        if(!(n % i)){
            factor += 2;
        }
    }

    return factor;
}
